export const ACC_CHARGED_CHANGED = 'ACC_CHARGED_CHANGED';
export const GETWAY_CHANGED = 'GETWAY_CHANGED';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const ADDRESS_ID_CHANGED = 'ADDRESS_ID_CHANGED';
export const DELIVERY_TYPE_CHANGED = 'DELIVERY_TYPE_CHANGED';
export const CAMPAGIN_CODE_CHANGED = 'CAMPAGIN_CODE_CHANGED';
export const BASKET_CHANGED = 'BASKET_CHANGED';

export const CHANGE_BASKET = 'CHANGE_BASKET';

